#!/usr/bin/env bash
# Launches the full PX4 + Gazebo + ROS 2 stack.
# Usage: bash ~/github_desktop/circe/gazebo/launch_baylands.sh

# ── WORLD ─────────────────────────────────────────────────────────────────────
GZ_WORLD="baylands"   # <── only line that differs between launch_default.sh and launch_baylands.sh
# ──────────────────────────────────────────────────────────────────────────────

set -e
export QT_QPA_PLATFORM=xcb
# Force Gazebo OGRE2 to use NVIDIA GPU on Wayland + Optimus.
# Session is Wayland (not X11) so prime-select nvidia alone doesn't redirect app rendering.
# renderD128=Intel(0x8086), renderD129=NVIDIA(0x10de) — without these vars OGRE2 picks Intel.
export __NV_PRIME_RENDER_OFFLOAD=1
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json

GAZEBO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PX4_DIR="$HOME/PX4-Autopilot"
ROS_SETUP="/opt/ros/jazzy/setup.bash"
WS_SETUP="$HOME/ws_px4/install/local_setup.bash"
WORLD_LABEL="${GZ_WORLD:-default}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}[launch]${NC} $*"; }
warn()  { echo -e "${YELLOW}[launch]${NC} $*"; }
error() { echo -e "${RED}[launch]${NC} $*"; exit 1; }

cleanup() {
    info "Shutting down..."
    kill $(jobs -p) 2>/dev/null
    pkill -f MicroXRCEAgent 2>/dev/null
    pkill -f "bin/px4" 2>/dev/null
    pkill -f "gcs_heartbeat\|parameter_bridge\|takeoff_hover" 2>/dev/null
    wait 2>/dev/null
    info "All processes stopped."
}
trap cleanup EXIT INT TERM

info "Killing any stale processes..."
pkill -f MicroXRCEAgent 2>/dev/null || true
pkill -f "bin/px4" 2>/dev/null || true
pkill -f "gz sim" 2>/dev/null || true
pkill -f "gcs_heartbeat\|takeoff_hover\|drone_detector\|parameter_bridge" 2>/dev/null || true
sleep 2

# Step 1: MicroXRCEAgent
info "Starting MicroXRCEAgent on port 8888..."
MicroXRCEAgent udp4 -p 8888 > /tmp/xrce.log 2>&1 &
sleep 2
grep -q "running" /tmp/xrce.log || error "MicroXRCEAgent failed to start. Check /tmp/xrce.log"
info "MicroXRCEAgent running."

# Step 2: PX4 SITL + Gazebo
info "Starting PX4 SITL + Gazebo (${WORLD_LABEL} world)..."
cd "$PX4_DIR"
[ -n "$GZ_WORLD" ] && export PX4_GZ_WORLD="$GZ_WORLD"
export PX4_GZ_MODEL_POSE="-2,-2,0,0,0,0"
make px4_sitl gz_x500 > /tmp/px4.log 2>&1 &
PX4_PID=$!

info "Waiting for 'Ready for takeoff!'..."
TIMEOUT=120
ELAPSED=0
while ! grep -q "Ready for takeoff" /tmp/px4.log 2>/dev/null; do
    sleep 2
    ELAPSED=$((ELAPSED + 2))
    if [ $ELAPSED -ge $TIMEOUT ]; then
        error "PX4 did not reach 'Ready for takeoff' in ${TIMEOUT}s. Check /tmp/px4.log"
    fi
    if ! kill -0 $PX4_PID 2>/dev/null; then
        error "PX4 process died. Check /tmp/px4.log"
    fi
done
info "PX4 ready."

# Step 3: GCS heartbeat + battery fix
info "Starting GCS heartbeat..."
python3 "$GAZEBO_DIR/gcs_heartbeat.py" > /tmp/gcs.log 2>&1 &
sleep 3
grep -q "Connected" /tmp/gcs.log || warn "GCS heartbeat may not have connected yet — check /tmp/gcs.log"
info "GCS heartbeat running."

# Step 4: Rover camera bridge
# Explorer R2 front camera topic is auto-generated by Gazebo (no <topic> tag in its SDF).
# Remapped to /rover_camera/image so drone_detector.py needs no changes.
info "Starting rover camera bridge..."
source "$ROS_SETUP"
source "$WS_SETUP"
ros2 run ros_gz_bridge parameter_bridge \
    "/world/${WORLD_LABEL}/model/rover_cam/link/link/sensor/camera/image@sensor_msgs/msg/Image[gz.msgs.Image" \
    --ros-args \
    -r "/world/${WORLD_LABEL}/model/rover_cam/link/link/sensor/camera/image:=/rover_camera/image" \
    > /tmp/bridge.log 2>&1 &
sleep 3
info "Camera bridge running."

# Step 4b: Rover cmd_vel bridge (ROS 2 → Gazebo, one-directional)
info "Starting rover cmd_vel bridge..."
ros2 run ros_gz_bridge parameter_bridge \
    "/rover/cmd_vel@geometry_msgs/msg/Twist]gz.msgs.Twist" \
    > /tmp/rover_bridge.log 2>&1 &
sleep 1
info "Rover cmd_vel bridge running."

info "──────────────────────────────────────────"
info "Sim stack is running. Press Ctrl+C to stop."
info "To fly the drone, start the web controller:"
info "  bash ~/github_desktop/circe/controller/run.sh"
info "  Then open http://localhost:8080"
info "──────────────────────────────────────────"
# Keep script alive (bridges run in background jobs)
wait
