"""Single source of truth for the dataset merge pipeline.

Everything the pipeline does — which sources to use, how each source's raw
classes map into the unified 13-class taxonomy, which folders/classes to drop and
WHY — is declared here. No mapping logic lives anywhere else.

Taxonomy (final trained classes), id = list index:
    0 concrete_crack  1 corrosion     2 fluid_patch     3 fire   4 smoke
    5 gauge_face      6 efflorescence 7 exposed_rebar   8 spalling
    9 missing_bolt   10 bolt_ok      11 bolt_defective 12 bolt_corroded
"""
from pathlib import Path

# ---- paths -------------------------------------------------------------
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                       # model_training/
DATASETS_DIR = ROOT / "datasets"         # READ-ONLY sources (never modified)
MERGED_DIR = ROOT / "merged_v2"          # OUTPUT (regenerated by 03_export). v2 = 13-class bolt
                                         # taxonomy; merged/ (11-class, what circe_yolo26n trained
                                         # on) is deliberately left intact for comparison.
REPORTS_DIR = ROOT / "reports"           # analysis figures + report + drop manifest
SPLIT_MANIFEST = REPORTS_DIR / "split_manifest.csv"   # stem -> split; pins held-out membership
                                         # across taxonomy changes (see 03_export.stratified_split)
FO_DATASET_NAME = "circe_inspection"     # FiftyOne dataset name (in its own DB)

# ---- taxonomy ----------------------------------------------------------
TAXONOMY = [
    "concrete_crack",   # 0
    "corrosion",        # 1
    "fluid_patch",      # 2
    "fire",             # 3
    "smoke",            # 4
    "gauge_face",       # 5
    "efflorescence",    # 6
    "exposed_rebar",    # 7
    "spalling",         # 8
    "missing_bolt",     # 9   (SDNET, COCO source - EMPTY-HOLE class, kept: see note below)
    "bolt_ok",          # 10  (dataset_annotation/ Gemini+SAM3 re-annotation)
    "bolt_defective",   # 11  (dataset_annotation/ Gemini+SAM3 re-annotation)
    "bolt_corroded",    # 12  (dataset_annotation/ Gemini+SAM3 re-annotation)
]
# Bolt-taxonomy change (this session): the three bolt_* classes come from the dataset_annotation/
# pipeline (Gemini 3-pass majority vote + SAM3 box tightening) and describe the CONDITION of a
# fastener that is PRESENT. `loose_bolt` was DROPPED because SDNET's "Loosen" boxes mark the same
# physical fastener the new scheme now labels bolt_defective/bolt_ok - two contradictory positive
# labels on identical pixels, which Ultralytics' multi-label BCE would silently train both heads on.
# `missing_bolt` is KEPT because it is NOT a contradiction: it marks an EMPTY HOLE, a different
# object in the same photo. Measured this session over the 199 overlapping SDNET images: of 437
# "Missing" boxes, 392 (90%) have IoU < 0.3 against ANY new box and 378 have exactly zero overlap
# (median best-IoU 0.000). The two annotations are complementary, so dropping missing_bolt would
# delete the "fastener absent" capability for no benefit.
NAME2ID = {n: i for i, n in enumerate(TAXONOMY)}

# ---- per-source class map ---------------------------------------------
# For every INCLUDED source folder: {source_class_id: target_name_or_None}.
# None = drop that class's boxes (image is kept; it may become a background/negative).
# Source class ids follow each folder's own data.yaml `names` order (verified this session).
CLASS_MAP = {
    "corrosion__meee-aegk9": {0: "corrosion"},                       # Corroded
    "crack-corrosion__codebrim": {                                   # CODEBRIM: 5 -> 5 of our 13
        0: "corrosion",        # CorrosionStain
        1: "concrete_crack",   # Crack
        2: "efflorescence",    # Efflorescence
        3: "exposed_rebar",    # ExposedBars
        4: "spalling",         # Spallation
    },
    "fire-smoke__ak-rfpt5": {0: "fire", 1: None, 2: "smoke"},        # 1 Other -> DROP
    "fire-smoke__yolov5-u5mjv": {0: "fire", 1: "fire", 2: "smoke"},  # 1 flame -> fire
    "fluid-patch__cv-6rgre": {0: "fluid_patch"},                     # Spill
    "fluid-patch__kuanhan-fu": {0: "fluid_patch", 1: None},          # 1 object -> DROP (motorbike)
    "fluid-patch__project-5v4jq": {0: "fluid_patch"},                # leak
    "fluid-patch__welding-defects": {0: "fluid_patch"},              # oil_spill
    "gauge-face__dataset-qxuat": {0: None, 1: "gauge_face", 2: None, 3: None, 4: None},  # keep 'gauge'
    "gauge-face__yolo-lxxyl": {0: None, 1: "gauge_face", 2: None},   # keep 'Gauge'
    # --- added datasets (folders keep their raw Roboflow slug names; datasets/ is immutable) ---
    "kashita1crack-spall-detector": {0: "concrete_crack", 1: "spalling"},   # cracks, spalling
    "uminho-gya54crack-detection-concrete-gphbn": {0: "concrete_crack"},    # crack
}

# Reasons a class's boxes are dropped (for the report — box-level, not image-level).
DROP_CLASS_REASON = {
    ("fire-smoke__ak-rfpt5", 1): "junk class 'Other' (people / watermarks / logos)",
    ("fluid-patch__kuanhan-fu", 1): "phantom class 'object' (single box on a parked motorbike)",
    ("gauge-face__dataset-qxuat", 0): "needle/tick keypoint 'center' (not the gauge dial)",
    ("gauge-face__dataset-qxuat", 2): "needle/tick keypoint 'max' (not the gauge dial)",
    ("gauge-face__dataset-qxuat", 3): "needle/tick keypoint 'min' (not the gauge dial)",
    ("gauge-face__dataset-qxuat", 4): "needle/tick keypoint 'tip' (not the gauge dial)",
    ("gauge-face__yolo-lxxyl", 0): "keypoint 'Center' (not the gauge dial)",
    ("gauge-face__yolo-lxxyl", 2): "keypoint 'Needle' (not the gauge dial)",
}

# Whole folders excluded from the merge, with the IMAGE-level drop reason.
# (gauge-face__kaushal-bhide was deleted by the user; SDNET is now imported via COCO below.)
EXCLUDE_FOLDERS = {}

# ---- COCO sources (imported via fo.types.COCODetectionDataset) --------
# SDNET ships COCO JSON. `category_map` remaps COCO category NAMES -> taxonomy; names absent from the
# map are dropped. `data_path`/`labels_path` are relative to DATASETS_DIR. The pre-drawn
# `output_images_with_*` folders are ignored — only the raw resized images are used.
SDNET = "bolt-defects__ext-sdnet2025"
COCO_SOURCES = {
    # Only the EMPTY-HOLE ("Missing") boxes are still taken from SDNET's own COCO labels; the
    # fastener-condition boxes for these same images now come from BOLT_YOLO_SOURCES below.
    # "Loosen" -> None drops those boxes rather than letting them contradict bolt_defective/bolt_ok
    # on identical pixels (see the TAXONOMY note above for the measured overlap evidence).
    "sdnet-missing_bolt": {
        "data_path": f"{SDNET}/Defected/Annotated Missing bolt & nuts/Resized- 640-640",
        "labels_path": f"{SDNET}/Defected/Annotated Missing bolt & nuts/Annotated File/annotations.coco.json",
        "category_map": {"Missing": "missing_bolt"},  # 'Missing-dPh5' + 'Loosen' -> dropped
    },
}

# ---- YOLO sources from the dataset_annotation/ Gemini+SAM3 pipeline ----
# Flat (unsplit) YOLO dirs: <path>/images/*.jpg + <path>/labels/*.txt, class ids per that pipeline's
# own 3-class data.yaml (0 bolt_ok, 1 bolt_defective, 2 bolt_corroded) remapped into TAXONOMY here.
# NOTE these live OUTSIDE DATASETS_DIR - they are produced by this repo, not downloaded read-only.
ANNOT_DIR = ROOT.parent / "dataset_annotation" / "circe_datasets"
BOLT_CLASS_MAP = {0: "bolt_ok", 1: "bolt_defective", 2: "bolt_corroded"}
BOLT_YOLO_SOURCES = {
    "gemini-npu_bolt":    ANNOT_DIR / "npu_bolt" / "dataset",
    "gemini-sdnet_bolt":  ANNOT_DIR / SDNET / "dataset",
}
# Extra folders of images with NO defects -> imported as background/negative samples.
BACKGROUND_DIRS = {
    "sdnet-fixed": f"{SDNET}/Fixed/640-640",
}

# ---- split / curation settings ----------------------------------------
SPLITS_ON_DISK = ["train", "valid", "test"]   # source folder split dir names
SPLIT_RATIOS = {"train": 0.70, "valid": 0.20, "test": 0.10}
SPLIT_SEED = 51

DUP_THRESH = 0.03            # distance threshold for near-duplicate detection (mobilenet embeddings).
# 0.03 is deliberately conservative: mobilenet-v2 embeddings conflate "similar defect texture" with
# "duplicate", so higher thresholds (e.g. 0.25) gut the rare classes (exposed_rebar 50->5,
# efflorescence 176->13). At 0.03 only near-identical frames are dropped (~4.7k of 59.8k); rare
# classes stay almost fully intact while the bloated single-source video-frame classes are trimmed.
BACKGROUND_MAX_SHARE = 0.15  # cap background (no-box) images at <=15% of each split
# Fast FiftyOne Zoo model for embeddings (dedup + UMAP). Per the fiftyone find-duplicates skill,
# mobilenet-v2 is the recommended fast model — CLIP is far slower and overkill for dedup.
EMBED_MODEL = "mobilenet-v2-imagenet-torch"

ENABLE_MISTAKENNESS = False  # needs a model-prediction pass; off by default (see README)

IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
