"""Single source of truth for the dataset merge pipeline.

Everything the pipeline does — which sources to use, how each source's raw
classes map into the unified 9-class taxonomy, which folders/classes to drop and
WHY — is declared here. No mapping logic lives anywhere else.

Taxonomy (final trained classes), id = list index:
    0 concrete_crack  1 corrosion   2 fluid_patch  3 fire   4 smoke
    5 gauge_face      6 efflorescence  7 exposed_rebar  8 spalling
"""
from pathlib import Path

# ---- paths -------------------------------------------------------------
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                       # model_training/
DATASETS_DIR = ROOT / "datasets"         # READ-ONLY sources (never modified)
MERGED_DIR = ROOT / "merged"             # OUTPUT (regenerated by 03_export)
REPORTS_DIR = ROOT / "reports"           # analysis figures + report + drop manifest
FO_DATASET_NAME = "circe_inspection"     # FiftyOne dataset name (in its own DB)

# ---- taxonomy ----------------------------------------------------------
TAXONOMY = [
    "concrete_crack",   # 0
    "corrosion",        # 1
    "fluid_patch",      # 2
    "fire",             # 3
    "smoke",            # 4
    "gauge_face",       # 5
    "efflorescence",    # 6
    "exposed_rebar",    # 7
    "spalling",         # 8
    "loose_bolt",       # 9   (SDNET, COCO source)
    "missing_bolt",     # 10  (SDNET, COCO source)
]
NAME2ID = {n: i for i, n in enumerate(TAXONOMY)}

# ---- per-source class map ---------------------------------------------
# For every INCLUDED source folder: {source_class_id: target_name_or_None}.
# None = drop that class's boxes (image is kept; it may become a background/negative).
# Source class ids follow each folder's own data.yaml `names` order (verified this session).
CLASS_MAP = {
    "corrosion__meee-aegk9": {0: "corrosion"},                       # Corroded
    "crack-corrosion__codebrim": {                                   # CODEBRIM: 5 -> 5 of our 9
        0: "corrosion",        # CorrosionStain
        1: "concrete_crack",   # Crack
        2: "efflorescence",    # Efflorescence
        3: "exposed_rebar",    # ExposedBars
        4: "spalling",         # Spallation
    },
    "fire-smoke__ak-rfpt5": {0: "fire", 1: None, 2: "smoke"},        # 1 Other -> DROP
    "fire-smoke__yolov5-u5mjv": {0: "fire", 1: "fire", 2: "smoke"},  # 1 flame -> fire
    "fluid-patch__cv-6rgre": {0: "fluid_patch"},                     # Spill
    "fluid-patch__kuanhan-fu": {0: "fluid_patch", 1: None},          # 1 object -> DROP (motorbike)
    "fluid-patch__project-5v4jq": {0: "fluid_patch"},                # leak
    "fluid-patch__welding-defects": {0: "fluid_patch"},              # oil_spill
    "gauge-face__dataset-qxuat": {0: None, 1: "gauge_face", 2: None, 3: None, 4: None},  # keep 'gauge'
    "gauge-face__yolo-lxxyl": {0: None, 1: "gauge_face", 2: None},   # keep 'Gauge'
    # --- added datasets (folders keep their raw Roboflow slug names; datasets/ is immutable) ---
    "kashita1crack-spall-detector": {0: "concrete_crack", 1: "spalling"},   # cracks, spalling
    "uminho-gya54crack-detection-concrete-gphbn": {0: "concrete_crack"},    # crack
}

# Reasons a class's boxes are dropped (for the report — box-level, not image-level).
DROP_CLASS_REASON = {
    ("fire-smoke__ak-rfpt5", 1): "junk class 'Other' (people / watermarks / logos)",
    ("fluid-patch__kuanhan-fu", 1): "phantom class 'object' (single box on a parked motorbike)",
    ("gauge-face__dataset-qxuat", 0): "needle/tick keypoint 'center' (not the gauge dial)",
    ("gauge-face__dataset-qxuat", 2): "needle/tick keypoint 'max' (not the gauge dial)",
    ("gauge-face__dataset-qxuat", 3): "needle/tick keypoint 'min' (not the gauge dial)",
    ("gauge-face__dataset-qxuat", 4): "needle/tick keypoint 'tip' (not the gauge dial)",
    ("gauge-face__yolo-lxxyl", 0): "keypoint 'Center' (not the gauge dial)",
    ("gauge-face__yolo-lxxyl", 2): "keypoint 'Needle' (not the gauge dial)",
}

# Whole folders excluded from the merge, with the IMAGE-level drop reason.
# (gauge-face__kaushal-bhide was deleted by the user; SDNET is now imported via COCO below.)
EXCLUDE_FOLDERS = {}

# ---- COCO sources (imported via fo.types.COCODetectionDataset) --------
# SDNET ships COCO JSON. `category_map` remaps COCO category NAMES -> taxonomy; names absent from the
# map are dropped. `data_path`/`labels_path` are relative to DATASETS_DIR. The pre-drawn
# `output_images_with_*` folders are ignored — only the raw resized images are used.
SDNET = "bolt-defects__ext-sdnet2025"
COCO_SOURCES = {
    "sdnet-loose_bolt": {
        "data_path": f"{SDNET}/Defected/Annotated Loosen bolt & nuts/Resized images 640-640",
        "labels_path": f"{SDNET}/Defected/Annotated Loosen bolt & nuts/Annotated File/_annotations.coco.json",
        "category_map": {"Loosen": "loose_bolt", "LOOSEN": "loose_bolt"},
    },
    "sdnet-missing_bolt": {
        "data_path": f"{SDNET}/Defected/Annotated Missing bolt & nuts/Resized- 640-640",
        "labels_path": f"{SDNET}/Defected/Annotated Missing bolt & nuts/Annotated File/annotations.coco.json",
        "category_map": {"Missing": "missing_bolt", "Loosen": "loose_bolt"},  # 'Missing-dPh5' -> drop
    },
}
# Extra folders of images with NO defects -> imported as background/negative samples.
BACKGROUND_DIRS = {
    "sdnet-fixed": f"{SDNET}/Fixed/640-640",
}

# ---- split / curation settings ----------------------------------------
SPLITS_ON_DISK = ["train", "valid", "test"]   # source folder split dir names
SPLIT_RATIOS = {"train": 0.70, "valid": 0.20, "test": 0.10}
SPLIT_SEED = 51

DUP_THRESH = 0.03            # distance threshold for near-duplicate detection (mobilenet embeddings).
# 0.03 is deliberately conservative: mobilenet-v2 embeddings conflate "similar defect texture" with
# "duplicate", so higher thresholds (e.g. 0.25) gut the rare classes (exposed_rebar 50->5,
# efflorescence 176->13). At 0.03 only near-identical frames are dropped (~4.7k of 59.8k); rare
# classes stay almost fully intact while the bloated single-source video-frame classes are trimmed.
BACKGROUND_MAX_SHARE = 0.15  # cap background (no-box) images at <=15% of each split
# Fast FiftyOne Zoo model for embeddings (dedup + UMAP). Per the fiftyone find-duplicates skill,
# mobilenet-v2 is the recommended fast model — CLIP is far slower and overkill for dedup.
EMBED_MODEL = "mobilenet-v2-imagenet-torch"

ENABLE_MISTAKENNESS = False  # needs a model-prediction pass; off by default (see README)

IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
