name: drone_detect
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.15
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - cuda-version=11.8
  - ultralytics=8.4.62
  - opencv=4.10.0
  - numpy=1.26.4
  - pip:
    - websockets
